# Generated by Django 3.0.5 on 2022-12-10 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221209_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 10, 14, 53, 405332)),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
